Add linearize option for Web Optimized PDF saving.
eol-uchile/pdfXBlock pull request #5
Opened 2024-04-19 13:00 UTC by tomaspemora

Also implement object hiding for embedded PDFs on devices with a screen width less than lg.

2024-04-19 13:24 UTC, fsologureng commented
Por qué opcional el linearizado? yo lo dejaría como parte del save siempre. No hay ningún efecto negativo en guardarlo así.

2024-04-19 14:49 UTC, tomaspemora commented
@fsologureng Modificado el commit para que incluya la opción de linearizado por defecto sin posibilidad de cambio

2024-04-22 14:50 UTC, fsologureng requested changes

2024-04-22 14:50 UTC, fsologureng commented on pdf/pdf.py
> +
Linea extra innecesaria

2024-04-22 14:50 UTC, fsologureng commented on pdf/tests.py
> +            'display_name' : "Test Block",
No es necesario el cambio de comillas; Soy de la idea de que no es bueno mezclar 2 tipos de comillas en un mismo objeto. El cambio sólo debiera remitirse al value de `"pdf_file"`.

2024-04-22 14:51 UTC, fsologureng commented
El test aplicado sobre la rama me funciona ok ahora.

2024-04-22 14:53 UTC, fsologureng reviewed
Tb podrías agregar en la glosa del commit que corregiste el test existente agregando el default de `is_downloadable`.

2024-05-22 13:54 UTC, tomaspemora commented
@fsologureng Actualicé un poco el código. Agregué el test que habíamos conversado y agregué un par de cosas. Los detalles están en el mensaje del commit.

2024-05-22 14:10 UTC, fsologureng approved these changes

2024-05-22 14:11 UTC, merged